# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CookBook' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookBook
	pod 'SideMenu'
	pod 'Alamofire', '~> 4.3'
	pod 'PKHUD', '~> 4.0'
end
